# Generated by Django 4.2.12 on 2024-05-29 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='Transaction_ID',
        ),
    ]
