# Generated by Django 4.2.12 on 2024-05-24 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='equipment_code',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='equipment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.assets', to_field='equipment_code'),
        ),
    ]
