# Generated by Django 4.2.12 on 2024-05-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0002_remove_transactions_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Transaction_type',
            field=models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT'), ('EDIT', 'EDIT')], max_length=5),
        ),
    ]
