# Generated by Django 4.2.12 on 2024-05-29 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0003_alter_transactions_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='equipment_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.assets'),
        ),
    ]
