# Generated by Django 4.2.12 on 2024-05-24 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0003_alter_allocated_user_alter_transactions_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='T_id',
            new_name='Transaction_ID',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='T_date',
            new_name='Transaction_date',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='T_type',
            new_name='Transaction_type',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='equipment_id',
            new_name='equipment_ID',
        ),
    ]
