# Generated by Django 4.2.12 on 2024-05-10 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0004_assets_assigned_on_assets_employee_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assets',
        ),
        migrations.DeleteModel(
            name='Assets1',
        ),
        migrations.DeleteModel(
            name='AssetType',
        ),
    ]
