# Generated by Django 4.2.12 on 2024-05-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0004_alter_transactions_equipment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocated',
            name='user',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='user',
            field=models.CharField(default='Not Assigned', max_length=50),
        ),
    ]
