# Generated by Django 4.2.12 on 2024-05-10 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventorymanager', '0005_delete_assets_delete_assets1_delete_assettype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.CharField(max_length=30)),
                ('equipment_name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('employee', models.CharField(default='Not Assigned', max_length=30)),
                ('assigned_on', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
