# Generated by Django 4.2.12 on 2024-05-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0005_alter_allocated_user_alter_transactions_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='in_out',
            field=models.BooleanField(default=False),
        ),
    ]
